"use client"
import * as React from "react"
import { Button } from "@/components/ui/button"
const SEARCH_LINES=["checking questionable directories...","asking the server nicely...","checking under the couch...","interrogating DNS...","blaming the frontend...","blaming the backend...","blaming the user...","retracting previous statement...","looking behind the cache...","page definitely isn't here."]
function response(c:string):string[]{switch(c){case"help":return["help  ls  whoami  pwd  sudo  clear  home  projects  secrets  hack  exit  definitely-not-a-trap"];case"ls":return["home/  projects/  definitely-not-secrets/","taxes-2009/  passwords.txt  404.exe"];case"whoami":return["somebody with way too much free time"];case"pwd":return["/amer/lol/where/the/hell/am/i"];case"sudo":return["amer is not in the sudoers file.","This incident will be reported.","Actually, this entire website is Amer's.","That's awkward."];case"secrets":return["Nice try.","I'm not giving you the answer key."];case"projects":return["Fetching projects...","No. Go look at the actual hub."];case"home":return["The command line cannot click links for you. Probably."];case"hack":return["INITIALIZING MAINFRAME...","BYPASSING FIREWALL...","ENHANCING...","ENHANCING...","ENHANCING...","ACCESSING THE MAINFRAME...","ERROR: We don't have a mainframe."];case"rm -rf /":return["Deleting Amer.lol...","12%  [██░░░░░░░░]","37%  [████░░░░░░]","64%  [██████░░░░]","89%  [█████████░]","99%  [██████████]","Permission denied.","nice try."];case"exit":return["You can leave the terminal, but the terminal never leaves you."];case"definitely-not-a-trap":return["It was a trap.","Fortunately, it was also poorly implemented."];case"":return[];default:return[`command not found: ${c}`,"The computer looks disappointed."]}}
export function SearchTerminal({run,onDone,onTerminalSecret}:{run:number;onDone:()=>void;onTerminalSecret:()=>void}){const[lines,setLines]=React.useState<string[]>([]);const[searching,setSearching]=React.useState(false);const[input,setInput]=React.useState("");const[commands,setCommands]=React.useState(0);const timers=React.useRef<ReturnType<typeof setTimeout>[]>([])
const finish=React.useCallback(()=>{timers.current.forEach(clearTimeout);timers.current=[];setLines(current=>current.includes("CASE CLOSED")?current:[...current,"CASE CLOSED","HTTP 404","We looked everywhere."]);setSearching(false);onDone()},[onDone])
React.useEffect(()=>{if(!run)return;timers.current.forEach(clearTimeout);setLines(["> searching amer.lol..."]);setSearching(true);const picked=[...SEARCH_LINES].sort(()=>Math.random()-.5).slice(0,6);picked.forEach((line,i)=>timers.current.push(setTimeout(()=>setLines(old=>[...old,`> ${line}`]),230*(i+1))));timers.current.push(setTimeout(finish,230*(picked.length+2)));return()=>timers.current.forEach(clearTimeout)},[run,finish])
function submit(e:React.FormEvent){e.preventDefault();const c=input.trim().toLowerCase();if(c==="clear")setLines([]);else setLines(old=>[...old,`$ ${input}`,...response(c)]);setInput("");if(c){const next=commands+1;setCommands(next);if(next>=3||c==="hack"||c==="rm -rf /")onTerminalSecret()}}
if(!run)return null;return <div className="mt-5 overflow-hidden rounded-xl border border-emerald-500/30 bg-[#07110c] text-left font-mono text-xs text-emerald-300 shadow-inner sm:text-sm"><div className="flex items-center justify-between border-b border-emerald-500/20 px-3 py-2 text-[10px] uppercase tracking-widest text-emerald-400/60"><span>amer.lol recovery shell</span>{searching&&<Button variant="ghost" size="sm" onClick={finish} className="h-6 px-2 font-mono text-[10px] text-emerald-300 hover:bg-emerald-400/10 hover:text-emerald-200">skip</Button>}</div><div className="max-h-56 min-h-32 overflow-y-auto p-3" aria-live="polite">{lines.map((line,i)=><div key={`${i}-${line}`} className={line==="CASE CLOSED"?"mt-2 font-bold text-white":"min-h-5"}>{line}</div>)}</div>{!searching&&<form onSubmit={submit} className="flex border-t border-emerald-500/20 px-3 py-2"><span aria-hidden>$&nbsp;</span><input aria-label="Terminal command" value={input} onChange={e=>setInput(e.target.value)} autoComplete="off" spellCheck={false} className="min-w-0 flex-1 border-0 bg-transparent p-0 text-emerald-200 outline-none"/><span className="animate-pulse" aria-hidden>▋</span></form>}</div>}
