"use client"
import * as React from "react"
import { Button } from "@/components/ui/button"
import { ArrowDown,ArrowLeft,ArrowRight,ArrowUp,X } from "lucide-react"
type Point={x:number;y:number};type Direction=Point
const SIZE=16,START=[{x:7,y:8},{x:6,y:8},{x:5,y:8}],MILESTONES:Record<number,string>={5:"Still lost.",10:"You're actually playing this?",20:"There are real pages on this website.",30:"Please consider going outside.",40:"Amer.lol Productivity Department has been notified.",50:"I genuinely did not plan for anyone to get this far."}
const randomFood=(snake:Point[])=>{let p:Point;do{p={x:Math.floor(Math.random()*SIZE),y:Math.floor(Math.random()*SIZE)}}while(snake.some(s=>s.x===p.x&&s.y===p.y));return p}
export function SnakeGame({best,onScore,onClose}:{best:number;onScore:(n:number)=>void;onClose:()=>void}){const[snake,setSnake]=React.useState<Point[]>(START);const[food,setFood]=React.useState<Point>({x:12,y:8});const[score,setScore]=React.useState(0);const[dead,setDead]=React.useState(false);const[direction,setDirection]=React.useState<Direction>({x:1,y:0});const directionRef=React.useRef(direction);const touch=React.useRef<Point|null>(null)
const steer=React.useCallback((next:Direction)=>{const current=directionRef.current;if(next.x+current.x===0&&next.y+current.y===0)return;directionRef.current=next;setDirection(next)},[])
React.useEffect(()=>{function key(e:KeyboardEvent){const map:Record<string,Direction>={ArrowUp:{x:0,y:-1},w:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1},ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0}};if(map[e.key]){e.preventDefault();steer(map[e.key])}}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[steer])
React.useEffect(()=>{if(dead)return;const id=setInterval(()=>setSnake(current=>{const d=directionRef.current;const head={x:current[0].x+d.x,y:current[0].y+d.y};if(head.x<0||head.y<0||head.x>=SIZE||head.y>=SIZE||current.some(p=>p.x===head.x&&p.y===head.y)){setDead(true);return current}const ate=head.x===food.x&&head.y===food.y;const next=[head,...current];if(ate){const nextScore=score+1;setScore(nextScore);onScore(nextScore);setFood(randomFood(next))}else next.pop();return next}),125);return()=>clearInterval(id)},[dead,food,onScore,score])
function restart(){setSnake(START);setFood({x:12,y:8});setScore(0);setDead(false);directionRef.current={x:1,y:0};setDirection({x:1,y:0})}
function swipeEnd(e:React.TouchEvent){const start=touch.current;if(!start)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;steer(Math.abs(dx)>Math.abs(dy)?{x:Math.sign(dx),y:0}:{x:0,y:Math.sign(dy)})}
return <div className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-background/95 p-4 backdrop-blur-md"><div className="w-full max-w-lg"><div className="mb-3 flex items-center justify-between"><div className="font-mono text-sm"><b>SCORE {String(score).padStart(2,"0")}</b><span className="ml-5 text-muted-foreground">BEST {Math.max(best,score)}</span></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Close game"><X/></Button></div><div className="relative aspect-square overflow-hidden rounded-2xl border bg-card shadow-2xl touch-none" onTouchStart={e=>touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}} onTouchEnd={swipeEnd}><div className="absolute inset-0 opacity-30" style={{backgroundImage:"linear-gradient(hsl(var(--border)) 1px,transparent 1px),linear-gradient(90deg,hsl(var(--border)) 1px,transparent 1px)",backgroundSize:`${100/SIZE}% ${100/SIZE}%`}}/>{snake.map((p,i)=><div key={`${p.x}-${p.y}`} className="absolute rounded-[3px] bg-primary" style={{left:`${p.x*100/SIZE}%`,top:`${p.y*100/SIZE}%`,width:`${100/SIZE}%`,height:`${100/SIZE}%`,opacity:1-i/(snake.length*1.5)}}/>)}<div className="absolute grid place-items-center rounded-sm bg-foreground font-mono text-[7px] font-black text-background" style={{left:`${food.x*100/SIZE}%`,top:`${food.y*100/SIZE}%`,width:`${100/SIZE}%`,height:`${100/SIZE}%`}}>404</div>{dead&&<div className="absolute inset-0 grid place-items-center bg-background/75 backdrop-blur-sm"><div className="text-center"><h3 className="text-3xl font-bold">GAME OVER</h3><p className="mb-4 text-sm text-muted-foreground">Even the snake found a dead end.</p><Button onClick={restart}>Try Again</Button></div></div>}</div><p className="mt-3 min-h-5 text-center text-sm text-muted-foreground">{MILESTONES[score]||"Use arrow keys, WASD, swipe, or the controls."}</p><div className="mx-auto mt-2 grid w-36 grid-cols-3 gap-1 sm:hidden"><span/><Button size="icon" variant="outline" onClick={()=>steer({x:0,y:-1})}><ArrowUp/></Button><span/><Button size="icon" variant="outline" onClick={()=>steer({x:-1,y:0})}><ArrowLeft/></Button><Button size="icon" variant="outline" onClick={()=>steer({x:0,y:1})}><ArrowDown/></Button><Button size="icon" variant="outline" onClick={()=>steer({x:1,y:0})}><ArrowRight/></Button></div></div></div>}
